### PR TITLE
Typography

### PR DESCRIPTION
**Pull request by jalendport**
Added new fonts and corresponding typography rules. Also added sample typography layout.

### CODE REVIEW

**Comment by rcdilorenzo** [comment]
Design looks excellent! I'll take a look at the code shortly.

**Comment by rcdilorenzo** [comment]
I've added a couple of comments, but I'm liking how this progresses. Thanks a million!

**Comment by jalendport** [comment]
@rcdilorenzo I think I've fixed as per your notes. Yeah in terms of the naming conventions, I sort of just followed the pattern you had, so I assume it's "correct".

**Comment by rcdilorenzo** [comment]
@jalenconner: I've modified the components styles so that it is not dependent on the `style.scss` file, which will not be put into the actual app and should only be used to add only the style guide's extra necessary styles. Good work!

**Comment by jalendport** [comment]
@rcdilorenzo the typography is not the same anymore... Is that on purpose?

**Comment by rcdilorenzo** [comment]
It should be pretty much the same. I just changed a little bit of sizing and a couple of font-weight things with the `h1`-`h6`. Does something not look right? If you have comments, please let me know.

**Pull request merged**
